language: python
python:
  - "3.6"
services:
  - docker
script:
  - docker build -t backend .
  - BACKEND_IMAGE=backend docker-compose -f docker-compose-ci.yml run backend /app/scripts/dev/run_tests.sh