apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    app: v1
  name: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        app: v1
    spec:
      containers:
      - image: sztymajakub/main:latest
        name: dev
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: cm
        args:
        - ./run_django.sh
        imagePullPolicy: Always
status: {}
